version: 1.0
skills:
  - pattern: '.*'  
    tokens: 
      TARGET: '[fxbank]+'
      TAG: '[\\d\\.]+'
    script:
      - echo $1
      - echo $2

  - pattern: '.*'      
    script:
      - echo $0   