version: 1.0
skills:
  - pattern: 'fxbank.*'
    tokens: 
      TARGET: 'fxbank'
      TAG: '[\d\.]+'
    script:
      - echo '{{.TARGET}} with tag {{.TAG}}'

  - pattern: 'send'
    tokens:
      CONVERSATION_ID: 'to\s*'
    script:
      - "curl -H \"Content-Type: application/json\" -X POST -d '{\"conversationId\": \"29:1u0eB2K6HZPu605COMMKJTF9l116lj7KvThSXxxxe3Dg\", \"text\": \"test\"}' https://f2g.site/bot/herald/api/message"

  - pattern: '.*'
    script:
      - "{{.COMMAND}}"