version: 1.0
skills:
  - pattern: 'fxbank.*'
    tokens: 
      TARGET: '[fxbank]+'
      TAG: '[\d\.]+'
    script:
      - echo '{{.TARGET}} with tag {{.TAG}}'

  - pattern: '.*'      
    script:
      - "{{.WORD}}"