version: 1.0
skills:
  - pattern: '.*'  
    tokens: 
      TARGET: '[fxbank]+'
      TAG: '[\\d\\.]+'
    script:
      - echo {{.TARGET}} with tag {{.TAG}}

  - pattern: '.*'      
    script:
      - echo $0   